### ISSUE TITLE
Endian confusion

### ISSUE THREAD

**Issue by francisdb** [tomlogic/pinmame-nvram-maps#19]
I'm confused on the `_endian` field at the root.

Doc mentions this:
`_endian: Default endian setting for all entries in the file. Defaults to true.`
But all files use `big` or `little` as values for that field, what does `true` mean?

`jm_12r.nv.json` uses `endian` at the root instead of `_endian`
https://github.com/tomlogic/pinmame-nvram-maps/blob/cc94e886ed26f354ba24d5ad92faf4454a4f0f14/jm_12r.nv.json#L9
Is this on purpose?

**Comment by tomlogic** [comment]
Nope, that's an error.  Default should be `big` endian, and the `jm_12r.nv.json` file should be using `_endian`.

Open to a PR on correcting both `README.md` and `jm_12r.nv.json`, or I can make the corrections.

**Comment by francisdb** [comment]
create 2 prs (#22 , #23 )
