### ISSUE TITLE
Auto format

### ISSUE THREAD

**Issue by francisdb** [tomlogic/pinmame-nvram-maps#26]
Preferably all json files would be formatted the same.

2 or 4 spaces?
Everything on a new line?

- [x] Ci validates formatting
- [x] README contains command to format
- [x] `.editorconfig` for editor, see https://editorconfig.org/

Options:
* use [jq command](https://github.com/jqlang/jq) `jq --indent 2 . file.json | sponge file.json` (sponge is part of moreutils)
* use node JSON.stringify / Python alternative
* use https://github.com/ddopson/underscore-cli
* add your own below

Reformat *.json and check if git reports any changes

This should also take care of #17

**Comment by tomlogic** [comment]
I liked the compactness of some of my formatting, but I'm seeing value in standardized formats with each element on a new line.  I liked the output of `jq` with indentation.  I like 2-space indentation as a compromise of the following choices:

- use tabs: small file that's still human-readable, viewer can select tabstops
- use 2 spaces: still relatively small, no need to set tab stops when viewing in terminal or online
- use 4 spaces: easier to see indentation if editing

I just did a test with `hs_l4.nv.json` with the following character counts:
- 4 spaces: 27,589
- 2 spaces: 20,439 (74%)
- tabs: 16,864 (61%)

Anyone editing (or consuming) the files can use `jq` themselves to switch to a preferred format.  For example, a project that uses the files in an embedded platform could strip the whitespace completely to minimize file size.  Someone manually editing a file can convert to 4-space indentation if they prefer it to 2 spaces.

I can start on a feature branch that adds the `.editorconfig` file, and documents using `jq` to format.  If we're happy with that, I can start on CI tests.  Once it's all looking good, we can do a "cleanup" commit that normalizes the existing JSON files.  I think that a shell script with the `jq` call would also be a good idea -- one that iterates through the passed filenames so it would work for one-offs or updating all files by using a `*.json` glob.

**Comment by tomlogic** [comment]
Starting on this work in branch [feature/standardize-json-formatting.](../tree/feature/standardize-json-formatting)

**Comment by francisdb** [comment]
+1 for 2 spaces
