### ISSUE TITLE
ts_lx5: Shadow Loop Champ wrong

### ISSUE THREAD

**Issue by francisdb** [tomlogic/pinmame-nvram-maps#27]
https://github.com/tomlogic/pinmame-nvram-maps/blob/66585178df1e574b5303c818462e806a6db50460/ts_lx5.nv.json#L71C7-L71C58

python code output

```
high_scores
-----------
Grand Champion: MAB 700,000,000
Best Agent #1: BRE 650,000,000
Best Agent #2: BCF 600,000,000
Best Agent #3: DTW 550,000,000
Best Agent #4: DWF 500,000,000
Buyin Champion: BRE 900,000,000
BuyIn Score #1: MAB 850,000,000
BuyIn Score #2: BCF 800,000,000
BuyIn Score #3: TEX 750,000,000
BuyIn Score #4: ASR 700,000,000

mode_champions
--------------
Shadow Loop Champ: TEX 200
```

![image](https://github.com/user-attachments/assets/85280e20-7090-44f7-96b6-80adc439c8f7)

Binary
`54 45 58 02 02 FF`  first 3 are TEX, the map picks `02 FF` as the count

Not sure what the correct values would be, length 1 or picking a value elsewhere or in the code ignoring that FF

*Side note, that field could use `"suffix": " loops" `*

**Comment by tomlogic** [comment]
I like the suffix.  The file is pulling initials from 8119 and loop count from 8100, which sounds incorrect.  I guess I need to get the ROM and do some testing by modifying the file and seeing which byte is the loop count.  I'm guessing single byte, but Is it 8122?  8123?  Actually 8100?  Is 0x11 a BCD 11 (assumed) or actually a integer 17?

**Comment by francisdb** [comment]
Still getting the 200 value instead of 2
```
mode_champions
--------------
Shadow Loop Champ: TEX 200
```
