### ISSUE TITLE
st_162h: 0-terminated string encoding needed?

### ISSUE THREAD

**Issue by francisdb** [tomlogic/pinmame-nvram-maps#34]
Something not 100% correct with Star Trek

The last score is defined as 2 chars where the rest is 3.
This is because the default last highscore is `T`, where this is encoded as `54 00 FF FF FF ...`
All other strings also have a `\0` appended at the end

![image](https://github.com/user-attachments/assets/c0e9351c-1df3-4ba9-91e1-abf047da42ed)

So to be correct the length should probably at least contain this `\0` and let the user indicate these string as `cstring` or `0-terminated` which is currently not available?

![image](https://github.com/user-attachments/assets/5523374a-324c-4d08-b120-28c38cb16e73)

https://github.com/tomlogic/pinmame-nvram-maps/blob/748b47961843cf8aa8a4706dfea49fd75341baa3/st_162h.nv.json#L21-L25

**Comment by tomlogic** [comment]
Is this one of the Stern games that allows 10-character or 12-character names as well?  If so, we need the full length, and I'll need to update the specification to call out null-termination for initials.

And is that really the correct location for the scores?  I see 0x017D7840 (25M) starting at 0x2F68 (12,136).

Also notable is the 16-bit checksum immediately after the high score entry.  Bytes from 0x2F70 to 0x2F8B add up to the (little-endian) 16-bit value at 0x2F8C.

**Comment by tomlogic** [comment]
Verified that null is always written to terminate the string, so the "initials" field is actually 11 characters long.  I have a PR out with updated maps, and will soon update the Python code.
