### ISSUE TITLE
Document `multiple_of` property for adjustments

### ISSUE THREAD

**Issue by tomlogic** [tomlogic/pinmame-nvram-maps#58]
As seen in `dm_lx4.nv.json`:

```
      "07": {
        "label": "Replay Start",
        "start": 6955,
        "encoding": "bcd",
        "length": 2,
        "min": 300,
        "max": 900,
        "multiple_of": 5,
        "default": 450,
        "suffix": "M"
      },
```

**Comment by francisdb** [comment]
And document that it applies to what he user-interface does. Not that the values should strictly adhere to it. Eg high score adjustment by 10000 on centaur where if updated by playing it can be any value.
