### ISSUE TITLE
_nibble_note & _note2 not defined in the spec

### ISSUE THREAD

**Issue by francisdb** [tomlogic/pinmame-nvram-maps#71]
https://github.com/tomlogic/pinmame-nvram-maps/blob/cba574ee36125f66d1db717297213084ff9f66d1/robo_a34.nv.json#L10

https://github.com/tomlogic/pinmame-nvram-maps/blob/cba574ee36125f66d1db717297213084ff9f66d1/hs_l4.nv.json#L100

https://github.com/tomlogic/pinmame-nvram-maps/blob/cba574ee36125f66d1db717297213084ff9f66d1/tsptr_l3.nv.json#L68

**Comment by tomlogic** [comment]
Good point.  I'll replace with `_note`, and combine into existing `_note` attributes when necessary.
