### ISSUE TITLE
Add guide for developers

### ISSUE THREAD

**Issue by tomlogic** [tomlogic/pinmame-nvram-maps#75]
The `README` file currently defines the map files in some detail, but someone new to the project might struggle with working out implementation details.

I see value in having a document that describes step-by-step how to build up a parser.  Developers need to know which properties to use for extracting a sequence of bytes from the `.nv` file, and then how to handle each encoding.

This could be a section in the `README`, or go into a separate file.

It would also be helpful to include a table of the different encodings, and how different properties affect those encodings.  For example, the `null` property only applies to `ch` encoding.  The `endian` property only applies to `bcd`, `bits`, and `int`.

**Comment by francisdb** [comment]
There are already 2 implementations that can be used as reference. And I think the audience for the library is rather small. So would not overdo this too much.

**Comment by tomlogic** [comment]
Good point.  I have a table in the README for #76 that indicates which properties apply to which encodings, which will hopefully help new implementors.  (I recently received questions from someone working on a C# implementation.)
